name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Go + Reuse
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: â¬‡ï¸ Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: go.mod

      - name: ğŸ” Golang lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: v2.5.0

      - name: ğŸ” Reuse lint
        run: |
          make lint-reuse