name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint Go + Reuse
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v5

      - name: â¬‡ï¸ Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: ğŸ” Golang lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: ğŸ” Reuse lint
        run: |
          make lint-reuse